[project]
name = "fhir-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Torben Lauritzen", email = "torlai@sundk.dk" }
]
requires-python = "==3.14.7"
dependencies = [
    "fhir-resources>=8.3.0",
    "nicegui>=3.17.1",
    "pywebview>=6.2.1",
]

[project.scripts]
fhir-hackathon = "fhir_hackathon:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
