[project]
name = "fhir-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Torben Lauritzen", email = "torlai@sundk.dk" }
]
requires-python = ">=3.14"
dependencies = [
    "fhir.resources==6.2.0",
    "pydantic<3.0,>=2.7.4",
    "fhirclient>=4.4.0",
    "fhirpy>=2.3.0",
    "requests",
    "nicegui>=3.17.1",
    "qtpy>=2.4.3",
    "python-dotenv>=1,<2",
]

[project.scripts]
fhir-hackathon = "fhir_hackathon:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
