[project]
name = "frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Torben Lauritzen", email = "torlai@sundk.dk" }
]
requires-python = ">=3.14"
dependencies = [
    "fhirpy>=2.3.0",
    "nicegui>=3.17.1",
    "qtpy>=2.4.3",
]

[project.scripts]
frontend = "frontend:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
